### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException Version 8.0.9

### ISSUE THREAD

**Issue by weenggs-dev** [zoho/salesiq-mobilisten-android-sample#54]
Fatal Exception: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
       at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
       at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
       at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
       at java.util.Objects.checkIndex(Objects.java:385)
       at java.util.ArrayList.get(ArrayList.java:434)
       at com.zoho.livechat.android.modules.messages.ui.fragments.ChatFragment.handleTriggerReplyMessage(ChatFragment.kt:3039)
       at com.zoho.livechat.android.modules.messages.ui.fragments.ChatFragment.doSendMessage(ChatFragment.kt:4935)
       at com.zoho.livechat.android.ui.adapters.viewholder.MessagesWidgetSelectionViewHolder$2.onClick(MessagesWidgetSelectionViewHolder.java:230)
       at android.view.View.performClick(View.java:7892)
       at android.view.View.performClickInternal(View.java:7869)
       at android.view.View.-$$Nest$mperformClickInternal()
       at android.view.View$PerformClick.run(View.java:30891)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by bhahirathan-mb-11956** [comment]
Hi @weenggs-dev,
 
We apologize for the inconvenience. This issue has been addressed in our current development build, and we hope to release it soon. I'll keep you posted on the updates.
 
We really appreciate your support and understanding. Meanwhile, please check out our [latest version](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/latest).
 
Best regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by weenggs-dev** [comment]
Hello Bhahirathan,

We already tried with the latest version, but we are still getting the same error with our existing onNewIntent code:

override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    setIntent(intent) // Important to update the internal reference
}


The error is:
Type mismatch: inferred type is Intent? but Intent was expected

This is not a custom method; it’s a native Android method. I don’t want to make major changes to the working project. Could you please suggest the required changes to make it compatible with Zoho?

**Comment by bhahirathan-mb-11956** [comment]
Hi @weenggs-dev ,
 
Thank you for reaching out to us. The `intent` parameter in the `onNewIntent(intent: Intent?)` method is non-null in the recent version of `androidx.activity:activity` dependency. So we suggest you remove the question mark shown in the below reference and verify once.
 
```
override fun onNewIntent (intent: Intent)
```

We recommend you update to the latest version [8.3.0](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/v8.3.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues along with the GitHub issue ID. We will be happy to help.
 
*Regards,*
*Bhahirathan M*
*Zoho SalesIQ.*
